name: Build SSM Helper
on: [push]

jobs:
    build:

        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - x86_64-unknown-linux-gnu
                    - x86_64-unknown-linux-musl
    
        steps:
            - uses: actions/checkout@v1
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  target: ${{ matrix.target }}
                  override: true
            - name: Build
              uses: actions-rs/cargo@v1
              with:
                  use-cross: true
                  command: build
                  args: --release --target=${{ matrix.target }}              
            - name: Run tests
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: cargo test --verbose
            - name: Strip Binary
              run: strip target/${{ matrix.target }}/release/ssm_helper
            - name: Save Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: ssm_helper-${{ matrix.target }}
                  path: target/${{ matrix.target }}/release/ssm_helper
    release:
        name: Generate Release
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target:
                    - x86_64-unknown-linux-gnu
                    - x86_64-unknown-linux-musl
        if: success() && contains(github.ref, 'tags')
        steps:
            - name: Get the version
              id: get_version
              run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
            - name: Retrieve Artifacts
              uses: actions/download-artifact@v1
              with:
                  name: ssm_helper-${{ matrix.target[0] }}
            - name: Retrieve Artifacts
              uses: actions/download-artifact@v1
              with:
                  name: ssm_helper-${{ matrix.target[1] }}
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: Release ${{ github.ref }}
                  draft: true
                  prerelease: false
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }} 
                  asset_path: ./ssm_helper-${{ matrix.target[0] }}
                  asset_name: ssm_helper-${{ matrix.target[0] }}
                  asset_content_type: application/zip
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1.0.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./ssm_helper-${{ matrix.target[1] }}
                  asset_name: ssm_helper-${{ matrix.target[1] }}
                  asset_content_type: application/zip